[build]
command = "source /opt/buildhome/.phpbrew/bashrc && phpbrew switch 5.6.32 && /opt/buildhome/.phpbrew/bin/composer require tightenco/jigsaw && ./vendor/bin/jigsaw build"
publish = "/build_local"
