[build]
command = "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer require tightenco/jigsaw && ./vendor/bin/jigsaw build"
publish = "/build_local"
