@extends('_layouts.master')
@section('head')
@include('_partials.home-head')
@endsection
@section('body')
@include('_partials.home-header')
@include('_partials.home-intro')
@include('_partials.home-who_we_are')
@include('_partials.home-what_we_do')
@include('_partials.home-why_us')
@include('_partials.home-contact')
@include('_partials.home-footer')
@include('_partials.home-scripts')
@endsection